#!/usr/bin/env python3
"""Extract translatable strings from data/SecretEntries.lua.

The data file's English text doubles as its own translation key (the gettext
model), so translators need a list of those strings rather than a set of ids to
match. This produces that list as a ready-to-fill Lua locale file.

    python tools/extract-strings.py [--locale deDE] [-o path]

Re-run it after adding secrets: strings already translated in an existing locale
file keep their translation, new ones arrive empty. Editing an English string
orphans its translation, which is the tradeoff the gettext model makes in
exchange for needing no keys at all.
"""

import argparse
import os
import re
import sys

BS = chr(92)
HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, os.pardir, "data", "SecretEntries.lua")

# Fields whose value is shown to the player. `name` is included because it is the
# display name for kinds the game has no localised name for (mystery, manual) --
# it is translated only where it is rendered, never where it is used to resolve a
# requires / stepsRef / partOf reference.
TRANSLATABLE = ("name", "label", "note", "source", "desc")


# A double-quoted Lua string, allowing backslash escapes inside. Built by
# concatenation rather than %-formatting: a single backslash substituted into a
# character class escapes the closing bracket instead of matching a backslash.
QUOTED = '"((?:[^"' + BS * 2 + ']|' + BS * 2 + '.)*)"'


def lua_strings(text, field):
    """Yield the value of every `field = "..."` assignment in `text`."""
    pattern = re.compile(r'\b' + field + r'\s*=\s*' + QUOTED)
    for match in pattern.finditer(text):
        yield match.group(1)


def collect(path):
    with open(path, encoding="utf-8") as handle:
        source = handle.read()

    seen = []
    unique = set()
    for field in TRANSLATABLE:
        for value in lua_strings(source, field):
            value = value.strip()
            # Nothing to translate in a bare number, a URL or an empty string.
            if not value or value in unique:
                continue
            if value.startswith("http"):
                continue
            unique.add(value)
            seen.append(value)
    return seen


def existing_translations(path):
    """Read T["english"] = "translated" pairs out of a locale file, if present."""
    if not path or not os.path.exists(path):
        return {}
    with open(path, encoding="utf-8") as handle:
        source = handle.read()
    pattern = re.compile(r'T\[\s*' + QUOTED + r'\s*\]\s*=\s*' + QUOTED)
    return {m.group(1): m.group(2) for m in pattern.finditer(source)}


def escape(value):
    return value.replace(BS, BS * 2).replace('"', BS + '"')


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--locale", default="deDE")
    parser.add_argument("-o", "--output")
    args = parser.parse_args()

    strings = collect(DATA)
    out_path = args.output or os.path.join(
        HERE, os.pardir, "localisation", "data", "%s.lua" % args.locale)
    known = existing_translations(out_path)

    lines = [
        "-- Data strings for %s." % args.locale,
        "--",
        "-- Generated by tools/extract-strings.py; safe to re-run, existing",
        "-- translations are preserved. Fill in the right-hand side; a line left",
        "-- empty or deleted falls back to the English on the left.",
        "--",
        "-- The English text is the lookup key, so changing it in the data file",
        "-- orphans the translation here and it needs re-filling.",
        "",
        'if GetLocale() ~= "%s" then return end' % args.locale,
        "",
        "local T = _G.SecretChecklistDataLocale or {}",
        "",
    ]

    filled = 0
    for value in strings:
        translation = known.get(value, "")
        if translation:
            filled += 1
        lines.append('T["%s"] = "%s"' % (escape(value), escape(translation)))

    lines += ["", "_G.SecretChecklistDataLocale = T", ""]

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines))

    print("%s: %d strings (%d already translated) -> %s"
          % (args.locale, len(strings), filled, os.path.normpath(out_path)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
